PR: 最小限構成でのメモアプリ実装
kei615ykhm/logic-loom-nextjs14 pull request #14
Opened 2024-09-08 13:59 UTC by kei615ykhm

## 概要
このプルリクエストでは、`feature/minimal-configuration`ブランチから`develop`ブランチへの統合を行います。主な目的は、簡易的な最小限構成でのメモアプリを作成し、今後のアップデートの土台を構築することです。

＊こちらは、コードレビューのご依頼とマージ認証を目的としたPRになります。

## 作業内容
- 型定義の作成 (`src/types/index.ts`)
- カスタムフックの作成 (`src/hooks/useMemos.ts`)
- メモフォームコンポーネントの作成 (`src/components/memos/MemoForm.tsx`)
- メモリストコンポーネントの作成 (`src/components/memos/MemoList.tsx`)
- メインページの作成 (`src/app/page.tsx`)

## 実装の変更点
issue #9 にて当初予定していたローカルストレージを使用した保存機能の実装は、以下の理由により保留としました：

1. ローカルストレージの実装と`useEffect`の使用に関して、再学習が必要だと判断したため
2. 最終的な目標が`Supabase`のデータベースを使用した保存機能であるため、学習効率を考慮し、ローカルストレージでの実装に時間をかけるべきではないと判断したため

詳細: Issue #10 （クローズ済み）
作業ブランチ: `experimental/use-local-server`

## 今後の予定
1. ESLintの設定と必要に応じたコード修正（Issue #11）
2. ダッシュボード機能の実装（Issue #12 ）
   - Parallel Routesを使用したダッシュボードレイアウトの作成
   - メモリスト機能の実装（検索機能含む）
   - メモ作成機能の実装
3. SWR/SSG対応の下地作り（Issue #13 ）
   - モーダルコンポーネントの作成（将来の実装用）
   - SWRの下地作り
4. Supabaseとの連携によるデータベース実装
5. 保存機能の実装
6. メモの編集機能の追加
7. メモの詳細ページの作成

なお、具体的な実装詳細については別途Issueを立ち上げ、そちらで管理します。

## レビュー時の注意点
- 現時点では編集と保存機能は実装されていないため、アプリの再読み込み時にデータが失われます
- コンポーネントの構造と型定義が適切かどうかご確認ください
- カスタムフックの実装が今後の拡張性を考慮したものになっているかご確認ください

## テスト
- [ ] メモの追加が正常に動作すること
- [ ] メモリストが正しく表示されること
- [ ] コンポーネント間のデータの受け渡しが適切に行われていること

ご確認よろしくお願いいたします。

2024-09-08 15:23 UTC, niaka3dayo commented on src/hooks/useMemos.ts
> +export const useMemos = () => {
[MAY] Reactには元々`useMemo`という名前の組み込みHookがあるため、この命名は混乱を招くので、名前を変更したほうがいいです。

2024-09-08 15:23 UTC, niaka3dayo commented on src/hooks/useMemos.ts
> +  const addMemo = (content: string) => {
[May] ハンドラなので、`handleAddMemo`などの名前が一般的です。

2024-09-08 15:23 UTC, niaka3dayo commented on src/hooks/useMemos.ts
> +  const deleteMemo = (id: string) => {
同上

2024-09-08 15:23 UTC, niaka3dayo commented on src/components/memos/MemoList.tsx
> +  onDelete: (id: string) => void; // メモ削除のための関数
[MAY] こういうコメントはTSDoc形式で書いておけば他の場所で使う際に、VSCodeではマウスオーバーでその説明を表示してくれるようになるはずなのでそのほうが便利です。

```suggestion
/** MemoListPropsコンポーネントのプロパティの型定義 */
interface MemoListProps {
  /** メモの配列 */
  memos: Memo[];
  /** メモ削除のための関数 */
  onDelete: (id: string) => void; 
```

2024-09-08 15:23 UTC, niaka3dayo commented on src/components/memos/MemoForm.tsx
> +    }
[SHOULD] `content.trim()`が返すのは文字列なので、この場合は`content`が空であったとしても空文字列を返すことになると思います。
確かに、空文字列を暗黙的にブール変換した場合は`false`になるのですが、暗黙的ブール変換はかなり可読性が悪く、不安なコードに見えます。
暗黙的ブール変換をやめ、早期リターンを使えばもう少し良いコードになると思います。

```suggestion
　　const trimedContent = content.trim();
　　
　　if(trimedContent.length < 1) {
　　  // 入力された文字が1文字もない場合は何もせず早期リターン
　　  return;
　　}
　　
　　onSubmit(content); // 親コンポーネントから渡されたonSubmit関数を実行
    setContent(""); // 入力値をリセット
```

参考:
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/trim

2024-09-11 13:38 UTC, kei615ykhm commented
@niaka3dayo ご返信が遅れて申し訳ございません。前回のコードレビューでいただいたフィードバックに基づいて修正を行いました。変更点を一つのコメントにまとめましたので、ご確認ください。

主な変更点：

1. 命名の変更：
   - `useMemos` → `useMemoManager` (Reactの組み込みhookとの競合を避けるため)
   - `useMemos.ts` → `useMemoManager.ts`
   - `addMemo` → `handleAddMemo`
   - `deleteMemo` → `handleDeleteMemo`

2. src/components/memos/MemoForm.tsx:
   - 暗黙的ブール変換を早期リターンに変更
   - 注意：提案された`trimd`を`trimmed`に修正
   （ご提案いただいた命名を誤植と判断）

3. 全体的なコードリファクタリング：
   対象ファイル：MemoForm.tsx, MemoList.tsx, useMemoManager.ts
   - TSDoc形式のコメントを導入し、コンポーネントや関数の役割、パラメータ、返り値の説明を追加
   - 不要なコメントを削除し、コードの自己説明性を向上

4. useMemoManager.ts:
   - カスタムフック全体と各関数にTSDocコメントを追加
   - memosステートに簡単な説明を追加

特に注目していただきたい点：
- 各ファイルでのTSDocの導入
- MemoForm.tsxでの早期リターンの実装

全体的にご提案いただいた内容以上の修正を行っていますが、とくにTSDoc形式でコメントを残すアプローチは関数や`props`のデータフローを見失いやすい私にとっては大きな問題解決につながると感じて全体的なリファクタリングを行いました。

ご確認よろしくお願いいたします！

2024-09-12 00:08 UTC, niaka3dayo requested changes

2024-09-12 00:08 UTC, niaka3dayo commented on src/components/memos/MemoForm.tsx
> + * @param props.onSubmit - フォーム送信時に呼び出される関数
[MAY] `@param`や`@returns`は`TypeScript`を用いた`React Component`ではまず使わないです。
なぜなら、`Props`の型情報にTSDocを書いた段階でもう同じ情報だからです。

2024-09-12 00:08 UTC, niaka3dayo commented on src/components/memos/MemoForm.tsx
> +  /** メモの内容を管理するstate */
[MAY] `useState`で使う状態までコメントするのは、さすがにやりすぎです。見ればわかるようなものはコメントを追記するべきではなく、初見でわからないような複雑なものだけにコメントをつけるべきです。

`const [content, setContent] = React.useState<string>("");`

これは明らかに、`content`というステートを定義し、それは`string`型の状態で初期値が`""`であるというふうにコード上で明示しているので、この`TSDoc`は完全に蛇足です。

2024-09-12 00:08 UTC, niaka3dayo commented on src/components/memos/MemoForm.tsx
> +export const MemoForm: React.FC<MemoFormProps> = ({ onSubmit }) => {
[MAY] 最近はアロー関数を使ったこっちの書き方は主流ではないですね。パフォーマンスや、IDEでの使いやすさから、以下のような書き方を推奨します。

```suggestion
export default function MemoForm({ onSubmit }: MemoFormProps): React.ReactElement {
```

2024-09-12 00:08 UTC, niaka3dayo commented on src/components/memos/MemoForm.tsx
> +       */}
[SHOULD] コンポーネントのリターンしている`children`の要素に対してのコメント、さすがにやりすぎです。
これをしたいなら、`input`を返すコンポーネントを切り分けて作ってください。

2024-09-12 00:08 UTC, niaka3dayo commented on src/components/memos/MemoForm.tsx
> +       */}
同上

2024-09-12 00:08 UTC, niaka3dayo commented on src/components/memos/MemoList.tsx
> +export const MemoList: React.FC<MemoListProps> = ({ memos, onDelete }) => {
[MAY] 上で指摘した内容と同じです。

2024-09-12 00:08 UTC, niaka3dayo commented on src/components/memos/MemoList.tsx
> +   * メモ削除のための関数
```suggestion
   * メモ削除のためのコールバック関数
```

2024-09-12 00:08 UTC, niaka3dayo commented on src/components/memos/MemoForm.tsx
> +   * フォーム送信時に呼び出される関数
```suggestion
   * フォーム送信時に呼び出されるコールバック関数
```

2024-09-12 00:08 UTC, niaka3dayo commented on src/components/memos/MemoForm.tsx
> +  const handleSubmit = (e: React.FormEvent) => {
[MAY] このままではこのコンポーネントが描画されるたびに、この関数も新しく描画され続けてしまうので、パフォーマンスの問題があります。`useCallback`でメモ化してください。

2024-09-12 00:08 UTC, niaka3dayo commented on src/hooks/useMemoManager.ts
> +  };
[MAY] ハンドラ各種、`useCallback`によるメモ化が必要です。また、なぜかこちらはTSDoc形式のコメントになっていないです。

2024-09-12 00:08 UTC, niaka3dayo commented on src/hooks/useMemoManager.ts
> +// メモの状態を管理するカスタムフック
[MAY] なぜかこちらは`TSDoc`形式になっていない

2024-09-12 00:08 UTC, niaka3dayo commented on src/hooks/useMemoManager.ts
> +  // クライアントサイドでのみローカルストレージにメモを保存
[MAY] コメント内容が間違っています。
ここでは、`localStorage`に保存されたメモをロードしてるのであって、保存しているわけではないです。

2024-09-12 00:08 UTC, niaka3dayo commented on src/hooks/useMemoManager.ts
> +    if (storedMemos) {
[SHOULD] 暗黙的ブール変換をやめましょう。

```suggestion
    if (storedMemos !== undefined && storedMemos !== null && storedMemos !== '') {
```

2024-09-12 00:08 UTC, niaka3dayo commented on src/hooks/useMemoManager.ts
> +      setMemos(JSON.parse(storedMemos));
[SHOULD] 直接`JSON.parse`で`localStorage`内の文字列を展開してますが、これだと想定外の値が入力されていた場合のエラーハンドリングや、あとから仕様の変更があった際にオブジェクトを正しい形にアップデートするときなどに不具合が生じますね。

一度変数に`JSON.parse`で展開した後に、その変数の内容が想定と合っているかどうかを判定し、その後正しい形に修正してから状態にセットしたほうがいいです。不正な値であった場合のエラーハンドリングを意識しましょう。

2024-09-12 00:09 UTC, niaka3dayo commented
@kei615ykhm 見ました

2024-09-16 17:05 UTC, kei615ykhm commented
@niaka3dayo ご提案やご指摘をもとにコードを修正しました。次のステップとして、`zod`ライブラリを使ったバリデーションチェックを実装予定です。

ただし、現在のブランチでは多くの実装を行ってしまったため、一度`develop`にマージし、新しいブランチで #16 のタスクを進めようと思います。

現時点でのコードにはまだ課題が残っていますが、作業を次のフェーズに進めるために、私の判断でマージを行います。`zod`によるバリデーションチェックと型安全なコードへのリファクタリングが完了次第、再度コードレビューをお願いしたいと考えています。

これまで多くのサポートをいただき、ありがとうございました。
引き続き、よろしくお願い致します。

2024-09-16 17:07 UTC, merged